# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MetaWeatherBold' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MetaWeatherBold
  pod 'Alamofire'

  target 'MetaWeatherBoldTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MetaWeatherBoldUITests' do
    # Pods for testing
  end

end
